#! /usr/bin/env python

from pwn import *
import re

host, port = '2018shell2.picoctf.com', 64706
context_level = 'critical'

s = remote(host, port)

prompt = s.recv()

#print prompt

binary = re.findall('the (.*) as a word', prompt)[0]
answer = hex(int(binary.replace(' ',''),2))[2:].decode('hex')

s.sendline(answer)

prompt = s.recv()

#print prompt
hexadecimal = re.findall('the (.*) as a word', prompt)[0]
answer = hexadecimal.decode('hex')

s.sendline(answer)

prompt = s.recv()

#print prompt
octal = re.findall('the (.*) as a word', prompt)[0]

#print [ int(x, hexadecimals = re.findall('the (.*) as a word', prompt)[0] ) for x in octal.split()]
answer = ''.join([ chr(int(x, 8)) for x in octal.split() ])

s.sendline(answer)

prompt = s.recv()

#print prompt

print re.findall('picoCTF{.*}', prompt)[0]

s.close()
